### ISSUE TITLE
Allow for automated updating of app

### ISSUE THREAD

**Issue by techninja** [evil-mad/robopaint#34] opened 2013-07-20 08:14 UTC
This could easily pull from a specified branch of this repo, or possibly even just go and pull a new rendered executable or .nw file.

Infrastructure and plan for this will need ot be flushed out, but it seems like a pretty important thing that most modern applications deal with in some decent fashion. This also probably relies heavily on implementing better versioning and release standards :tangerine:

**Comment by oskay** [comment] 2015-01-29 19:14
A minimally annoying version would have a message that is displayed on the splash screen saying "A new version (1.0.1) is available. Click here to download."  It wouldn't need to interrupt what you're doing.

OTOH, it may be helpful to be a total PITA if there's an urgent security update.

**Comment by docprofsky** [comment] 2016-09-28 02:43
Closing because duplicate of #163.

**Closed by docprofsky** 2016-09-28 02:43 UTC
Labels: duplicate, enhancement, ui/ux
