### ISSUE TITLE
Extreme slowness when tracing certain files

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#262] opened 2016-06-10 17:07 UTC
Attached are two example files where RoboPaint seems to hang in the tracing stage. One of them is a very simple file, but still after 1 hour is in tracing (see screenshot).

(I have not verified this except on the Mac.)

![nothing after 1 hour screenshot](https://cloud.githubusercontent.com/assets/1009180/15972380/13e8bc88-2ef3-11e6-8863-f2849e1270fd.png)

[RoboPaintFails.zip](https://github.com/evil-mad/robopaint/files/309426/RoboPaintFails.zip)

**Comment by docprofsky** [comment] 2016-06-13 02:43
This is half fixed/bypassed.
evil-mad/robopaint@b3374fa fixes the problem with `nothing after 1 hour.svg`, but `nothing.svg` is still breaking RP.

Each file is causing problems in different places.
`nothing after 1 hour.svg` here https://github.com/evil-mad/robopaint/blob/e3f8e5b7d13cc2ccd6ef7a15bdee2e32175e4a20/resources/rp_modules/paper.auto.fill.js#L757
`nothing.svg` here https://github.com/evil-mad/robopaint/blob/bcebe2e23e8b22dfe51b50a6b7eff0c77ec8cb6f/resources/rp_modules/paper.auto.stroke.js#L313

Additional information can be found here.
https://gitter.im/evil-mad/robopaint?at=575e16a0e42570166a84616d

**Comment by docprofsky** [comment] 2016-07-16 19:32
I have done more testing on these files and have added some more fixes for them. They are in the flatten-fix branch. I believe I have found all of the problems caused by the files for all except the overlay fill types.

Should I open a PR for flatten-fix?

**Comment by Reff99** [comment] 2016-07-17 14:58
Hello - I'm the person with the problem, who first sent the files. As a relatively non-technical person, can someone tell me if there is now an update which lets me now paint these and other files (these were just two examples: I couldn't reproduce nearly every file I tried). Thanks!

**Comment by techninja** [comment] 2016-07-17 19:19
Once testing is done and the remaining fixes has been merged we should be in good shape to roll there next beta release _very soon_. @docprofsky has been finding and fixing bugs so it's good we're sticking with our current plan.

**Comment by Reff99** [comment] 2016-07-17 20:05
Ok, thanks a lot
Brian
>

**Comment by docprofsky** [comment] 2016-07-17 23:09
@Reff99 Can you run the `flatten-fix` branch and see if you still get any issues with it?

**Comment by oskay** [comment] 2016-07-17 23:23
@docprofsky: If you're going to ask a question like that, you should provide explicit instructions for how to test it. For example, is there a compiled version available to test somewhere? Or, if an existing RoboPaint install can be modified by replacing certain files, please describe how to do so.

**Comment by ajpiano** [comment] 2016-07-18 21:19
With @docprofsky's branch and help I was able to get "Nothing after 1 hr.svg" to print successfully and also got some other pieces to trace and begin printing more or less "successfully" as well :) Seems like this is... better than what's there !

**Closed** 2016-07-19 01:16 UTC
Labels: bug, critical

**Comment by oskay** [comment] 2016-08-30 21:10
Fantastic-- thank you for following up!
